# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.5
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix, --unsafe-fixes]
      # Run the formatter.
      - id: ruff-format

  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: uv run pyright
        language: system
        types: [python]
        pass_filenames: false
        always_run: true

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks

  # - repo: local
  #   hooks:
  #     - id: pytest
  #       name: pytest
  #       entry: uv run pytest tests/ -v --tb=short
  #       language: system
  #       pass_filenames: false
  #       always_run: true
